version: '3.3'
services:

  # 数据库
  db:
    image: mariadb
    network_mode: hosting_running_network
    restart: always
    expose:
      - 3306
    # ports:
    #   - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123 # 自行生成
    container_name: db_mariadb
